module.exports.config = {
  name: "meme",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Mr Chand",
  description: "Chaeyoung Pictures.",
  commandCategory: "Image",
  cooldowns: 1,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/2YpLtS7.jpeg",
"https://i.imgur.com/2U6ZsLI.jpeg",
"https://i.imgur.com/7JHCJXX.jpeg",
"https://i.imgur.com/wiQsALL.jpeg",
"https://i.imgur.com/VKVryDl.jpeg",
"https://i.imgur.com/bXWt2Vo.jpeg",
"https://i.imgur.com/UVwl7G0.jpeg",
"https://i.imgur.com/71lly7P.jpeg",
"https://i.imgur.com/lLo5zIa.jpeg",
"https://i.imgur.com/Lrrr2al.jpeg",
"https://i.imgur.com/whAl9JL.jpeg",
"https://i.imgur.com/qydW9aP.jpeg",
"https://i.imgur.com/nt2hH5R.jpeg",
"https://i.imgur.com/V9iLIdl.jpeg",
"https://i.imgur.com/9lNqYDF.jpeg",
"https://i.imgur.com/0zwDU8K.jpeg",
"https://i.imgur.com/1lR1afn.jpeg",
"https://i.imgur.com/JujY4IN.jpeg",
"https://i.imgur.com/zY5pWuJ.jpeg",
"https://i.imgur.com/7yJRlW4.jpeg",
"https://i.imgur.com/JVCupvz.jpeg",
"https://i.imgur.com/SqZdP6u.jpeg",
"https://i.imgur.com/H6D31XO.jpeg",
"https://i.imgur.com/5jjn61J.jpeg",
"https://i.imgur.com/8HCgJxW.jpeg",
"https://i.imgur.com/ZyyCLIS.jpeg",
"https://i.imgur.com/ZR4BCvi.jpeg",
"https://i.imgur.com/ZhSeoiw.jpeg",
"https://i.imgur.com/qaxUUXU.jpeg",
"https://i.imgur.com/DbuYSgN.jpeg",
"https://i.imgur.com/PfhHDi7.jpeg",
"https://i.imgur.com/jZva1h2.jpeg",
"https://i.imgur.com/0iclBu5.jpeg",
"https://i.imgur.com/InRwtPh.jpeg",
"https://i.imgur.com/WBbDIQV.jpeg",
"https://i.imgur.com/37bfgmq.jpeg",
"https://i.imgur.com/usLhexF.jpeg",
"https://i.imgur.com/xRKENLc.jpeg",
"https://i.imgur.com/leDbcJy.jpeg",
"https://i.imgur.com/vbjs6D3.jpeg",
"https://i.imgur.com/wTJRPLz.jpeg",
"https://i.imgur.com/uIKEpkf.jpeg",
"https://i.imgur.com/StgmMWh.jpeg",
"https://i.imgur.com/iBLYxcI.jpeg",
"https://i.imgur.com/ZmrhDAp.jpeg",
"https://i.imgur.com/4BeUjFP.jpeg",
"https://i.imgur.com/30xKCX7.jpeg",
"https://i.imgur.com/kzRBOFD.jpeg",
"https://i.imgur.com/KS6bP7v.jpeg",
"https://i.imgur.com/Po2rVsT.jpeg",
"https://i.imgur.com/6TDPFcF.jpeg",
"https://i.imgur.com/p5zTIvK.jpeg",
"https://i.imgur.com/GwxQ3LA.jpeg",
"https://i.imgur.com/2C74tSt.jpeg",
"https://i.imgur.com/k1I1I2N.jpeg",
"https://i.imgur.com/9I141q7.jpeg",
"https://i.imgur.com/dTWjsMG.jpeg",
"https://i.imgur.com/ZLeYjUh.jpeg",
"https://i.imgur.com/acFQf0P.jpeg",
"https://i.imgur.com/I3HVUwo.jpeg",
"https://i.imgur.com/xecwUPK.jpeg",
"https://i.imgur.com/f3CupKY.jpeg",
"https://i.imgur.com/g05BeJt.jpeg",
"https://i.imgur.com/PHIgeGL.jpeg",
"https://i.imgur.com/3uQo7ps.jpeg",
"https://i.imgur.com/7VrPuD6.jpeg",
"https://i.imgur.com/WPt0M6q.jpeg",
"https://i.imgur.com/Y4P7JrS.jpeg",
"https://i.imgur.com/rrXAwSi.jpeg",
"https://i.imgur.com/MV7TnBr.jpeg",
"https://i.imgur.com/7BzdX55.jpeg",
"https://i.imgur.com/TpgOXEu.jpeg",
"https://i.imgur.com/KWPHYCr.jpeg",
"https://i.imgur.com/HoxWbaB.jpeg",
"https://i.imgur.com/bQRpgaR.jpeg",
"https://i.imgur.com/zAx2S5a.jpeg",
"https://i.imgur.com/jQ6Q0Ib.jpeg",
"https://i.imgur.com/Gu37pbd.jpeg",
"https://i.imgur.com/Zj2F5fs.jpeg",
"https://i.imgur.com/Ezwfvrg.jpeg",
"https://i.imgur.com/qRhS7Iu.jpeg",
"https://i.imgur.com/BHVBrC3.jpeg",
"https://i.imgur.com/hpWNMPa.jpeg",
"https://i.imgur.com/hA4Mv0J.jpeg",
"https://i.imgur.com/fyYv0uv.jpeg",
"https://i.imgur.com/abzca0q.jpeg",
"https://i.imgur.com/9xAGPoj.jpeg",
"https://i.imgur.com/BPzcsAC.jpeg",
"https://i.imgur.com/bliznUS.jpeg",
"https://i.imgur.com/DViPwAR.jpeg",
"https://i.imgur.com/M48rF5x.jpeg",
"https://i.imgur.com/LCb7Rk8.jpeg",
"https://i.imgur.com/0SNyPz9.jpeg",
"https://i.imgur.com/m5gezsf.jpeg",
"https://i.imgur.com/pRwgUMv.jpeg",
"https://i.imgur.com/eBhcrI5.jpeg",
"https://i.imgur.com/q9UQ4c1.jpg",
"https://i.imgur.com/bJOPOe7.jpg",
"https://i.imgur.com/2gihJLT.jpg",
"https://i.imgur.com/nuRbXNA.jpg",
"https://i.imgur.com/QPjDQhC.jpg",
"https://i.imgur.com/ANTFbY8.jpg",
  ];
	 var callback = () => api.sendMessage({body:`😂𝐀𝐌𝐈𝐑 𝐄𝐃𝐈𝐓𝐎𝐑😂 \nNumber of photos available: ${link.length}`,attachment: fs.createReadStream(__dirname + "/cache/5.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.jpg"));	
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.jpg")).on("close",() => callback());
   };